name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbe25b2d4d4d32e11d27ebde614400fb61d248a26cc198789007393223ec4848"

[versions]
fabric = "0.15.2"
minecraft = "1.19.2"
