name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43dcf1c8aa3eea2147c3aa2711114443f19ca8deccbf1725e4bd17aa44cdd3a2"

[versions]
fabric = "0.16.14"
minecraft = "1.20.4"
