name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "220fe124eb5c112fda0afdf52312b40deb007845779c963c8abb153d852e10ec"

[versions]
fabric = "0.16.14"
minecraft = "1.20.4"
