name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47def70cc74f6d723946c7145d3f149db70511225c162ded5b74f979024fb227"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
