name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e469119cd1af9d1f09229beda0f1e97543379076df98ebeb3d49a1cfc5a0ae0"

[versions]
fabric = "0.16.14"
minecraft = "1.20.4"
