name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d02dcead67ea5c4745b275bb6542aa0617d08fefd2f3bd89e4ab4c2ccb021086"

[versions]
fabric = "0.16.14"
minecraft = "1.20.4"
