name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62a7f46f607bbb636383941ba226fc7d1f8cc2d73ba806d70bb64b75e7849094"

[versions]
fabric = "0.16.14"
minecraft = "1.20.4"
