name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3abf2949fe21f0866c4cdb2f64f961a66b7782835d0f848b52c8b0fcef7b7bba"

[versions]
fabric = "0.15.2"
minecraft = "1.19.2"
