name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3123fa541ae4a35b718e35481e0db8658d774c9da45ac5cdafbc787ff0a23c39"

[versions]
fabric = "0.16.14"
minecraft = "1.20.4"
