name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e19ac5b4c3347aed08389e093ae776d634540e804bdfcacc01fe4ab15b59c23d"

[versions]
fabric = "0.16.14"
minecraft = "1.20.4"
