name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46021037e925b6361d0f787e37e9ae7b7cc72519c2dd932cb40a61de11c900f5"

[versions]
fabric = "0.16.14"
minecraft = "1.20.4"
