name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f7707de541c4de4f9f847001317a3075a2cf0e3de632ce01b9f999fa58326ab"

[versions]
fabric = "0.15.2"
minecraft = "1.19.2"
